[package]
name = "dir-ageism"
version = "0.12.0"
authors = ["jonathan gerber <jlgerber@gmail.com>"]
edition = "2018"

[[bin]]
name = "amble"
path = "src/amble.rs"

[dependencies]
walkdir = "2.2.7"
structopt = "0.2.14"
failure = "0.1.5"
ignore = "0.4.6"
crossbeam-channel = "0.3.8"
colored = "1.7.0"
