[package]
name = "dir-ageism"
version = "0.1.0"
authors = ["jonathan gerber <jlgerber@gmail.com>"]
edition = "2018"

[[bin]]
name = "amble"
path = "src/amble.rs"

[dependencies]
walkdir = "2.2.7"
structopt = "0.2.14"
failure = "0.1.5"
